[selection]
fg = "light_yellow"
bold = true

[visual_mode_selection]
fg = "light_red"
bold = true

## [selection.prefix]
## prefix = "  "
## size = 2

[executable]
fg = "light_green"
bold = false

[regular]
fg = "white"

[directory]
fg = "light_blue"
bold = false

[link]
fg = "cyan"
bold = false

[link_invalid]
fg = "red"
bold = false

[socket]
fg = "light_magenta"
bold = false

[ext]

bmp.fg	= "yellow"
gif.fg	= "yellow"
heic.fg	= "yellow"
jpg.fg	= "yellow"
jpeg.fg	= "yellow"
pgm.fg	= "yellow"
png.fg	= "yellow"
ppm.fg	= "yellow"
svg.fg	= "yellow"

wav.fg	= "white"
flac.fg = "white"
mp3.fg	= "white"
amr.fg	= "white"
avi.fg	= "white"
flv.fg	= "white"
m3u.fg	= "white"
m4a.fg	= "white"
m4v.fg	= "white"
mkv.fg	= "white"
mov.fg	= "white"
mp4.fg	= "white"
mpg.fg	= "white"
rmvb.fg	= "white"
webm.fg	= "white"
wmv.fg	= "white"

7z.fg	= "red"
bz2.fg	= "red"
gz.fg	= "red"
rar.fg	= "red"
tar.fg	= "red"
tgz.fg	= "red"
xz.fg	= "red"
zip.fg	= "red"
