require("plugin_config.mason")
require("plugin_config.colorscheme")
require("plugin_config.treesitter")
require("plugin_config.telescope")
require("plugin_config.vim-test")
require("plugin_config.cmp")
require("plugin_config.lspsaga")
require("plugin_config.gitsigns")
require("plugin_config.copilot")
require("plugin_config.rust_config")
require("plugin_config.dap_config")
require("plugin_config.lazygit")
require("plugin_config.suda")
require("plugin_config.nvim-autopairs")
require("plugin_config.substitute")
require("plugin_config.translate")

