require("plugins.mason")
require("plugins.colorscheme")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.vim-test")
require("plugins.cmp")
require("plugins.lspsaga")
require("plugins.gitsigns")
require("plugins.copilot")
require("plugins.rust_config")
require("plugins.dap_config")
require("plugins.lazygit")
require("plugins.suda")
require("plugins.nvim-autopairs")
require("plugins.substitute")
require("plugins.translate")

